version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8501:8501"
    environment:
      - NAME=World
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=Pass@1234
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=Pass@1234
    depends_on:
      - mysql
      - postgres

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Pass@1234
      MYSQL_DATABASE: xdr_data
    ports:
      - "3306:3306"

  postgres:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Pass@1234
      POSTGRES_DB: xdr_data
    ports:
      - "5432:5432"